import {escapeHTML as e,playSound} from './helpers.js';
import {feedback} from './feedback.js';
import {animateAnswerResult,animateFeedback,enhancePressInteractions,transitionQuestion} from './motion.js';
export function quizScreen(root,ctx){
  const session=ctx.session;if(!session){ctx.navigate('/');return;}
  if(session.finished){ctx.navigate('/results');return;}
  const q=session.current&&!session.answered?session.current:session.next(),exam=session.options.mode==='exam';
  const total=Number.isFinite(session.limit)?session.limit:'∞',number=session.answers.length+1;
  const modeLabel=exam?'EXAMEN':session.options.mode==='survival'?'SURVIE':session.options.preset==='daily'?'RÉVISIONS DU JOUR':session.options.preset==='confusion'?'À NE PAS CONFONDRE':session.options.preset==='course'?'RÉVISION DU COURS':'EN RÉVISION';
  root.innerHTML=`<div class="quiz-progress"><div class="row question-meta"><span class="eyebrow">${modeLabel}</span><span class="session-count">Question ${number} / ${total}</span><button id="stop" type="button" class="button text">Terminer</button></div><progress aria-label="Progression de la session : question ${number} sur ${total}" ${total==='∞'?'':`value="${session.answers.length}" max="${session.limit}"`}></progress></div><section class="card question-card" aria-labelledby="question-prompt"><div class="row question-context"><span class="badge">${e(q.notion.matiere)}</span>${!exam?`<span class="quiz-combo" aria-label="${session.options.mode==='survival'?session.lives+' vies restantes':'Combo '+session.combo}">${session.options.mode==='survival'?'❤️'.repeat(session.lives):'🔥 '+session.combo}</span>`:''}</div><p class="eyebrow question-theme">${q.revenge?'🌱 REVANCHE · ':''}${e(q.notion.theme)}</p><h1 id="question-prompt" class="question-prompt">${e(q.prompt)}</h1><div id="response-area">${q.type==='qcm'?`<div class="answers" role="group" aria-label="Réponses proposées">${q.options.map((option,i)=>`<button type="button" class="answer" data-answer="${e(option.id)}"><span class="answer-letter" aria-hidden="true">${'ABCD'[i]}</span><span>${e(option.label)}</span></button>`).join('')}</div>`:`<form id="answer-form"><label class="field" for="answer-input">${e(q.answerLabel||'Quel est le terme ?')}<input id="answer-input" type="text" autocomplete="off" autocapitalize="sentences" enterkeyhint="done" maxlength="200" placeholder="Ta réponse…" required></label><button class="button primary wide" type="submit">Valider</button></form>`}<div class="question-actions">${!exam&&q.type==='text'?'<button id="hint" type="button" class="button text">💡 Indice</button>':'<span></span>'}<button id="skip" type="button" class="button text">Je ne sais pas</button></div><p id="hint-text" role="status" class="small muted"></p></div><div id="feedback-area" aria-live="polite" aria-atomic="false"></div></section>`;
  let submitting=false;
  function submit(value,skip=false){if(submitting)return;submitting=true;root.querySelectorAll('#response-area button,#response-area input').forEach(control=>control.disabled=true);const a=session.submit(value,skip);if(!a){submitting=false;return;}ctx.persist();if(exam){if(session.finished)ctx.navigate('/results');else ctx.navigate('/play');return;}
    root.querySelectorAll('[data-answer]').forEach(b=>{if(b.dataset.answer===value)b.classList.add('selected');if(b.dataset.answer===q.notion.id)b.classList.add('correct');else if(b.dataset.answer===value)b.classList.add('incorrect');else b.classList.add('answer-muted');});
    playSound(['exact','almost'].includes(a.result),ctx.user.settings);
    root.querySelector('#feedback-area').innerHTML=feedback(a,ctx.bank,session.combo)+`<div class="feedback-actions"><button id="next" type="button" class="button primary wide">${session.finished?'Voir mes résultats':'Continuer'} <i class="ph ph-arrow-right" aria-hidden="true"></i></button></div>`;
    const next=root.querySelector('#next'),goNext=()=>session.finished?ctx.navigate('/results'):ctx.navigate('/play');next.onclick=()=>transitionQuestion(root.querySelector('.question-card'),goNext);animateAnswerResult(root.querySelector('.answer.selected'));animateFeedback(root.querySelector('.feedback'));enhancePressInteractions(root.querySelector('#feedback-area'));next.scrollIntoView({block:'nearest',behavior:'smooth'});
  }
  root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submit(b.dataset.answer));
  const form=root.querySelector('#answer-form');if(form)form.onsubmit=event=>{event.preventDefault();const input=root.querySelector('#answer-input');if(input.value.trim())submit(input.value.trim());};
  root.querySelector('#skip').onclick=()=>submit('',true);
  const hint=root.querySelector('#hint');if(hint)hint.onclick=()=>{session.hint=true;hint.disabled=true;root.querySelector('#hint-text').textContent=`Première lettre : ${q.notion.terme[0].toUpperCase()}`;};
  root.querySelector('#stop').onclick=()=>{session.finish();ctx.persist();ctx.navigate('/results');};
  const heading=root.querySelector('h1');heading.tabIndex=-1;if(!matchMedia('(pointer: coarse)').matches)heading.focus({preventScroll:true});window.scrollTo(0,0);
}

